FROM node:20-alpine
RUN apk add --no-cache g++ make
WORKDIR /app
COPY package*.json ./
RUN npm install && npm install --save-dev nodemon
COPY . .
EXPOSE 8080
CMD ["npx", "nodemon", "--legacy-watch", "--env-file", ".env", "src/index.js"]
