export const SUBJECTS = [
  'DSA',
  'OS',
  'DBMS',
  'CN',
  'OOPs',
  'OOD',
  'System Design',
  'Tech Stack',
  'Resume Cross Questions',
  'Resume Roasting',
]

export const TOPICS = {
  DSA: [
    'Arrays & Strings',
    'Linked Lists',
    'Stacks & Queues',
    'Trees & Graphs',
    'Sorting & Searching',
    'Recursion & Backtracking',
    'Dynamic Programming',
    'Greedy Algorithms',
    'Hashing',
  ],
  OS: [
    'Processes & Threads',
    'Scheduling',
    'Memory Management',
    'Virtual Memory',
    'File Systems',
    'Deadlocks',
    'Synchronization',
    'I/O Systems',
  ],
  DBMS: [
    'Relational Model & SQL',
    'Normalization',
    'Transactions & ACID',
    'Indexing & B-Trees',
    'Query Optimization',
    'NoSQL',
    'Concurrency Control',
  ],
  CN: [
    'OSI & TCP/IP Model',
    'HTTP & HTTPS',
    'TCP vs UDP',
    'DNS',
    'IP Addressing & Subnetting',
    'Routing',
    'Sockets',
    'TLS/SSL',
  ],
  OOPs: [
    'Classes & Objects',
    'Inheritance',
    'Polymorphism',
    'Encapsulation & Abstraction',
    'SOLID Principles',
    'Design Patterns',
  ],
  OOD: [
    'Requirements Analysis',
    'Class Diagram Design',
    'Relationships (has-a, is-a)',
    'Common OOD Problems',
  ],
  'System Design': [
    'Scalability',
    'Load Balancing',
    'Caching',
    'Databases at Scale',
    'Message Queues',
    'Microservices',
    'CAP Theorem',
    'API Design',
  ],
  'Tech Stack': [
    'Languages & Frameworks Used',
    'Architecture Decisions',
    'Trade-offs',
    'Deployment',
  ],
  'Resume Cross Questions': [
    'Projects',
    'Internships',
    'Technical Decisions',
    'Challenges Faced',
  ],
  'Resume Roasting': ['Resume Analysis'],
}
